# GitHub Sponsors configuration
# Private repo olsa bile bu dosya sponsor button'u gösterir

# GitHub Sponsors hesabı aktif olunca bu satırı aç:
# github: rehberim360

# Şimdilik custom link kullan
custom: ['https://yapayzekachatbot.com/sponsor', 'https://github.com/sponsors/rehberim360']
